apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: go-helloworld-3
  name: go-helloworld-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-helloworld-3
  template:
    metadata:
      labels:
        app: go-helloworld-3
    spec:
      containers:
      - image: ghcr.io/eridon-pro/go-helloworld-3:f99c558ed8b8dcbf602813b2ab6fb90d11fe5a73@sha256:4dc96bdda7f2a6ee52e473f1774d9d3675cbe5d2237ed18fbf8828c73eed0c2b
        name: go-helloworld-3
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: go-helloworld-3
  name: go-helloworld-3
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: go-helloworld-3
  type: NodePort
