apiVersion: v1
kind: Service
metadata:
  labels:
    app: go-helloworld-3
  name: go-helloworld-3
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: go-helloworld-3
  type: NodePort
