apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: go-helloworld-3
  name: go-helloworld-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-helloworld-3
  template:
    metadata:
      labels:
        app: go-helloworld-3
    spec:
      containers:
      - image: ghcr.io/eridon-pro/go-helloworld-3:ee3cc57ee2d792c2d20c7efcb12a81c34702c7d5
        name: go-helloworld-3
