apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: go-helloworld-3
  name: go-helloworld-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-helloworld-3
  template:
    metadata:
      labels:
        app: go-helloworld-3
    spec:
      containers:
      - image: ghcr.io/eridon-pro/go-helloworld-3:16cef61fcaee518b0c7099f003ee1b4734708b77
        name: go-helloworld-3
