apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: go-helloworld-3
  name: go-helloworld-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-helloworld-3
  template:
    metadata:
      labels:
        app: go-helloworld-3
    spec:
      containers:
      - image: ghcr.io/eridon-pro/go-helloworld-3:1e71a225f760ec9f9dc0ae66e2f39059853a90b8@sha256:cd06f1850e601c2b4a9938a1c1ddf0e18c99483f99b28b330602f40e05d367d6 
        name: go-helloworld-3
