apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: go-helloworld-3
  name: go-helloworld-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-helloworld-3
  template:
    metadata:
      labels:
        app: go-helloworld-3
    spec:
      containers:
      - image: ghcr.io/eridon-pro/go-helloworld-3:1d130e0ecef7db5cd9d44d9e48a3f0081e2f558d@sha256:190ff328eaa5840cf1f912d2859c246f70ea9517e29675d625fe5eaa66bcde3b
        name: go-helloworld-3
