apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: go-helloworld-3
  name: go-helloworld-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-helloworld-3
  template:
    metadata:
      labels:
        app: go-helloworld-3
    spec:
      containers:
      - image: ghcr.io/eridon-pro/go-helloworld-3:sha-a4dd716580227e4cce62f60460853a1ca29d1fde
        name: go-helloworld-3
