apiVersion: batch/v1
kind: Job
metadata:
  name: pre-sync-scan
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: cosign-verify
        image: ghcr.io/sigstore/cosign/cosign:latest
        env:
          - name: IMAGE_REF
            value: ghcr.io/eridon-pro/go-helloworld-3:sha-a4dd716580227e4cce62f60460853a1ca29d1fde
        command: ["cosign", "verify", 
          "--certificate-oidc-issuer", "https://token.actions.githubusercontent.com", 
          "--certificate-identity-regexp", "^https://github.com/eridon-pro/go-helloworld-3/", 
          "$(IMAGE_REF)"]
      - name: trivy-scan
        image: aquasec/trivy:latest
        env:
          - name: IMAGE_REF
            value: ghcr.io/eridon-pro/go-helloworld-3:sha-a4dd716580227e4cce62f60460853a1ca29d1fde
        command: ["trivy", "image", "--exit-code", "1", "--severity", "HIGH,CRITICAL", "$(IMAGE_REF)"]
  backoffLimit: 1
