name: "CI Pipeline"

on:
  push:
    branches:
      - main

jobs:
  Build:
    # [skip ci] を含むコミットはこのジョブをトリガーしない
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      # 1. リポジトリのコードをチェックアウト
      - name: checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      # 2. 静的解析：GolangCI-Lint を実行
      - name: Run GolangCI-Lint
        #uses: golangci/golangci-lint-action@v3
        uses: golangci/golangci-lint-action@main
      #  with:
      #    version: v1.50.1
      #    version: latest

      # 3. テストの実行
      - name: Run tests
        run: go test -v ./...

      # 4. GoSec によるセキュリティスキャン
      - name: Run GoSec Security Scanner
        uses: securego/gosec@master
        with:
          # GoSec の引数を指定（プロジェクト全体をスキャン）
          args: ./...

      # 5. OWASP Dependency Check による SCA スキャン
      - name: Run OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "go-helloworld-3"
          path: "."
          format: "ALL"
          # 脆弱性の CVSS が 7.0 以上の場合はビルドを失敗させる設定（必要に応じて変更可）
          args: >
            --failOnCVSS 7
            --enableRetired

      # 6. GitHub Container Registry (ghcr.io) へのログイン
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 7. Docker Buildx のセットアップ（マルチプラットフォーム対応）
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest

      # 8. Docker イメージのビルド＆プッシュ
      - name: Build and Publish
        run: |
          docker buildx build \
            --push \
            --platform linux/arm/v7,linux/amd64 \
            -t ghcr.io/eridon-pro/go-helloworld-3:${{ github.sha }} \
            -t ghcr.io/eridon-pro/go-helloworld-3:latest \
            .

      # 9. Cosign のインストール
      - name: Install Cosign and Sign image with GitHub OIDC Token
        uses: sigstore/cosign-installer@v3.8.1

      # 10. GitHub OIDC トークンを利用した署名（コミットSHAタグのイメージに対して）
      - name: Sign commit SHA image with GitHub OIDC Token
        env:
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
          TAG: ghcr.io/eridon-pro/go-helloworld-3:${{ github.sha }}
        run: |
          cosign sign --yes ${TAG}@${DIGEST}

      # 11. Trivy によるイメージスキャン
      - name: Scan Docker Image with Trivy
        # Latest as of 20250320
        #uses: aquasecurity/trivy-action@0.30.0
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/eridon-pro/go-helloworld-3:${{ github.sha }}
          format: table
          exit-code: '1'
          severity: HIGH,CRITICAL

      # 12. SBOM の生成（Anchore sbom-action を利用）
      - name: Generate SBOM with Anchore SBOM Action
        uses: anchore/sbom-action@main
        with:
          image: ghcr.io/eridon-pro/go-helloworld-3:${{ github.sha }}
          output_format: cyclonedx-json
          output_file: sbom-${{ github.sha }}.json

      # 13. SBOM アーティファクトのアップロード
      - name: Upload SBOM Artifact
        uses: actions/upload-artifact@main
        with:
          name: sbom
          path: sbom-${{ github.sha }}.json

      # 14. マニフェストの更新
      - name: Update manifest with new image tag
        run: |
          NEW_TAG=${{ github.sha }}
          MANIFEST_FILE="manifest/deployment.yaml"
          # マニフェスト内の image フィールドを新しいタグに置換
          sed -i "s|ghcr.io/eridon-pro/go-helloworld-3:.*|ghcr.io/eridon-pro/go-helloworld-3:${NEW_TAG}|g" ${MANIFEST_FILE}
          git config user.name "eridon-pro"
          git config user.email "take@erikawa.com"
          git add ${MANIFEST_FILE}
          # コミットメッセージに [skip ci] を追加して、push による再トリガーを防止
          #git commit -m "Update deployment image tag to ${NEW_TAG}"
          git commit -m "Update deployment image tag to ${NEW_TAG} [skip ci]"
          # リモート URL を PAT を含む形に設定
          git remote set-url origin "https://${{ secrets.PAT_TOKEN }}@github.com/eridon-pro/go-helloworld-3.git"
          git push origin main

      # 15. Dependency Check レポートのアップロード
      - name: Upload Dependency Check Reports
        uses: actions/upload-artifact@main
        with:
          name: dependency-check-reports
          path: reports/

      # 16. Notify Discord on failure
      #- name: Notify Discord on failure
      #  if: failure()
      #  run: |
      #    curl -X POST -H "Content-Type: application/json" \
      #    --data '{"content": "CI pipeline for go-helloworld-3 failed! Please check the logs."}' \
      #    ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: CI Pipeline Success
        uses: rjstone/discord-webhook-notify@v1
        if: success()
        with:
          severity: info
          details: CI Pipeline Succeeded!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
      - name: CI Pipeline Failure
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
          severity: error
          details: CI Pipeline Failed! Check PR Log.
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
      - name: CI Pileline Cancelled
        uses: rjstone/discord-webhook-notify@v1
        if: cancelled()
        with:
          severity: warn
          details: CI Pileline Cancelled!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
