name: "CI Pipeline"

on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      # 1. リポジトリのコードをチェックアウト
      - name: checkout
        uses: actions/checkout@v2

      # 2. 静的解析：GolangCI-Lint を実行
      - name: Run GolangCI-Lint
        uses: golangci/golangci-lint-action@v3
      #  with:
      #    version: v1.50.1

      # 3. テストの実行
      - name: Run tests
        run: go test -v ./...

      # 4. GitHub Container Registry (ghcr.io) へのログイン
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 5. Docker Buildx のセットアップ（マルチプラットフォーム対応）
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest

      # 6. Docker イメージのビルド＆プッシュ
      - name: Build and Publish
        run: |
          docker buildx build \
            --push \
            --platform linux/arm/v7,linux/amd64 \
            -t ghcr.io/eridon-pro/go-helloworld-3:${{ github.sha }} .

      # 7. Trivy によるイメージスキャン
      - name: Scan Docker Image with Trivy
        # Latest as of 20250320
        uses: aquasecurity/trivy-action@0.30.0
        with:
          image-ref: ghcr.io/eridon-pro/go-helloworld-3:${{ github.sha }}
          format: table
          exit-code: '1'
          severity: HIGH,CRITICAL
